/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('./app/components/Back.vue')['default']
    Bg: typeof import('./app/components/Bg.vue')['default']
    ClientOnly: typeof import('./app/components/ClientOnly.vue')['default']
    CommandCommandPalette: typeof import('./app/components/command/CommandPalette.vue')['default']
    CommandPalette: typeof import('./app/components/command/CommandPalette.vue')['default']
    ContentProseH1: typeof import('./app/components/content/ProseH1.vue')['default']
    ContentProseH2: typeof import('./app/components/content/ProseH2.vue')['default']
    ContentProseH3: typeof import('./app/components/content/ProseH3.vue')['default']
    ContentProseH4: typeof import('./app/components/content/ProseH4.vue')['default']
    ContentProseH5: typeof import('./app/components/content/ProseH5.vue')['default']
    ContentProseH6: typeof import('./app/components/content/ProseH6.vue')['default']
    ContentProsePre: typeof import('./app/components/content/ProsePre.vue')['default']
    Cursor: typeof import('./app/components/Cursor.vue')['default']
    DarkToggle: typeof import('./app/components/DarkToggle.vue')['default']
    GC: typeof import('./app/components/GC.vue')['default']
    Home: typeof import('./app/components/Home.vue')['default']
    IconsBilibili: typeof import('./app/components/icons/IconsBilibili.vue')['default']
    IconsBlueSky: typeof import('./app/components/icons/IconsBlueSky.vue')['default']
    IconsElk: typeof import('./app/components/icons/IconsElk.vue')['default']
    IconsIconsBilibili: typeof import('./app/components/icons/IconsBilibili.vue')['default']
    IconsIconsBlueSky: typeof import('./app/components/icons/IconsBlueSky.vue')['default']
    IconsIconsElk: typeof import('./app/components/icons/IconsElk.vue')['default']
    IconsIconsNuxt: typeof import('./app/components/icons/IconsNuxt.vue')['default']
    IconsIconsOnuUI: typeof import('./app/components/icons/IconsOnuUI.vue')['default']
    IconsIconsUnoCSS: typeof import('./app/components/icons/IconsUnoCSS.vue')['default']
    IconsIconsUnPreset: typeof import('./app/components/icons/IconsUnPreset.vue')['default']
    IconsIconsVite: typeof import('./app/components/icons/IconsVite.vue')['default']
    IconsIconsVitest: typeof import('./app/components/icons/IconsVitest.vue')['default']
    IconsIconsVue: typeof import('./app/components/icons/IconsVue.vue')['default']
    IconsIconsX: typeof import('./app/components/icons/IconsX.vue')['default']
    IconsNuxt: typeof import('./app/components/icons/IconsNuxt.vue')['default']
    IconsOnuUI: typeof import('./app/components/icons/IconsOnuUI.vue')['default']
    IconsUnoCSS: typeof import('./app/components/icons/IconsUnoCSS.vue')['default']
    IconsUnPreset: typeof import('./app/components/icons/IconsUnPreset.vue')['default']
    IconsVite: typeof import('./app/components/icons/IconsVite.vue')['default']
    IconsVitest: typeof import('./app/components/icons/IconsVitest.vue')['default']
    IconsVue: typeof import('./app/components/icons/IconsVue.vue')['default']
    IconsX: typeof import('./app/components/icons/IconsX.vue')['default']
    ImgBlurHash: typeof import('./app/components/ImgBlurHash.vue')['default']
    MeAvatar: typeof import('./app/components/me/Avatar.vue')['default']
    MeInfo: typeof import('./app/components/me/Info.vue')['default']
    NavHeader: typeof import('./app/components/nav/NavHeader.vue')['default']
    NavNavFooter: typeof import('./app/components/nav/NavFooter.vue')['default']
    NavNavHeader: typeof import('./app/components/nav/NavHeader.vue')['default']
    OriginController: typeof import('./app/components/origin/Controller.vue')['default']
    OriginFullQuadrant: typeof import('./app/components/origin/FullQuadrant.vue')['default']
    OriginQuadrant: typeof import('./app/components/origin/Quadrant.vue')['default']
    PageHeader: typeof import('./app/components/PageHeader.vue')['default']
    Photos: typeof import('./app/components/photos/Photos.vue')['default']
    PhotosPhotoDetail: typeof import('./app/components/photos/PhotoDetail.vue')['default']
    PhotosPhotos: typeof import('./app/components/photos/Photos.vue')['default']
    Posts: typeof import('./app/components/posts/Posts.vue')['default']
    PostsIndex: typeof import('./app/components/posts/PostsIndex.vue')['default']
    PostsPosts: typeof import('./app/components/posts/Posts.vue')['default']
    PostsPostsIndex: typeof import('./app/components/posts/PostsIndex.vue')['default']
    Projects: typeof import('./app/components/projects/Projects.vue')['default']
    ProjectsProjects: typeof import('./app/components/projects/Projects.vue')['default']
    ProjectsRepoCard: typeof import('./app/components/projects/RepoCard.vue')['default']
    ProjectsSkeleton: typeof import('./app/components/projects/Skeleton.vue')['default']
    ProseHeading: typeof import('./app/components/ProseHeading.vue')['default']
    Timer: typeof import('./app/components/Timer.vue')['default']
    Toc: typeof import('./app/components/Toc.vue')['default']
  }
}
