shellEmulator: true
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  workerd: true
minimumReleaseAgeExclude:
  - taze@19.14.0

shamefullyHoist: true
autoInstallPeers: true
strictPeerDependencies: false

overrides:
  '@vue/server-renderer': 3.5.39
  vue: 3.5.39
