/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5c67ad4b58f5d253d6b6cc3bf3f2f084)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	GITHUB_USERNAME: string;
	NUXT_GITHUB_TOKEN: string;
	NUXT_ADMIN_PASSWORD: string;
	NUXT_SESSION_SECRET: string;
	SITE_PRESENCE: DurableObjectNamespace<import("./worker").SitePresence>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "SitePresence";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_USERNAME" | "NUXT_GITHUB_TOKEN" | "NUXT_ADMIN_PASSWORD" | "NUXT_SESSION_SECRET">> {}
}
