/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b38e448125c6136c2937ff59abdacede)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	GITHUB_USERNAME: string;
	NUXT_GITHUB_TOKEN: string;
	NUXT_ADMIN_PASSWORD: string;
	NUXT_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_USERNAME" | "NUXT_GITHUB_TOKEN" | "NUXT_ADMIN_PASSWORD" | "NUXT_SESSION_SECRET">> {}
}
