name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set node
        uses: actions/setup-node@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 📝 Lint
        run: pnpm lint
